version: 2.1
orbs:
  # Install node, aws-cli, eb-cli
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # Jobs are called later in the workflows section
jobs:
  build:
    docker:
      # Create Image
      - image: 'cimg/node:14.15'
    steps:
      # Install node and checkout code
      - node/install:
          node-version: '14.15'
      - checkout
      # Install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # Install dependencies in the the backend API
      - run:
          name: Install API Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run api:install
      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Build the backend API
      - run:
          name: API Build
          command: |
            npm run api:build
  # Deploy step will run only after manual approval
  deploy:
    docker:
      - image: 'cimg/base:stable'
      # Setup for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup
      - checkout
      # Deploy the backend API (install dependencies, build, set env variables, deploy)
      - run:
          name: Deploy API
          command: |
            npm run api:deploy
      # Deploy the frontend app (install dependencies, build, deploy)
      - run:
          name: Deploy Front End
          command: |
            npm run frontend:deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
